// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package http

import (
	"github.com/google/uuid"
)

// Defines values for ProjectRunOutputState.
const (
	Cancelled ProjectRunOutputState = "cancelled"
	Failure   ProjectRunOutputState = "failure"
	Pending   ProjectRunOutputState = "pending"
	Running   ProjectRunOutputState = "running"
	Success   ProjectRunOutputState = "success"
)

// ErrMsg defines model for ErrMsg.
type ErrMsg struct {
	Message string `json:"message"`
}

// Project defines model for Project.
type Project struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// ProjectArray defines model for ProjectArray.
type ProjectArray = []Project

// ProjectRunOutput defines model for ProjectRunOutput.
type ProjectRunOutput struct {
	ID        uuid.UUID             `json:"id"`
	ProjectID uuid.UUID             `json:"project_id"`
	State     ProjectRunOutputState `json:"state"`
	Success   bool                  `json:"success"`
}

// ProjectRunOutputState defines model for ProjectRunOutput.State.
type ProjectRunOutputState string

// ProjectRunOutputArray defines model for ProjectRunOutputArray.
type ProjectRunOutputArray = []ProjectRunOutput

// Scenario defines model for Scenario.
type Scenario struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	ProjectID uuid.UUID `json:"project_id"`
	Spec      string    `json:"spec"`
	SpecType  string    `json:"spec_type"`
}

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	// Limit The number of projects to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset The number of projects to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetRunsForProjectParams defines parameters for GetRunsForProject.
type GetRunsForProjectParams struct {
	// Limit The number of runs to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset The number of runs to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = Project

// CreateScenarioJSONRequestBody defines body for CreateScenario for application/json ContentType.
type CreateScenarioJSONRequestBody = Scenario
