// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	domain "github.com/inquiryproj/inquiry/internal/repository/domain"
)

// Project is an autogenerated mock type for the Project type
type Project struct {
	mock.Mock
}

// CreateProject provides a mock function with given fields: ctx, project
func (_m *Project) CreateProject(ctx context.Context, project *domain.CreateProjectRequest) (*domain.Project, error) {
	ret := _m.Called(ctx, project)

	var r0 *domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CreateProjectRequest) (*domain.Project, error)); ok {
		return rf(ctx, project)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CreateProjectRequest) *domain.Project); ok {
		r0 = rf(ctx, project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.CreateProjectRequest) error); ok {
		r1 = rf(ctx, project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Project) GetByID(ctx context.Context, id uuid.UUID) (*domain.Project, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Project, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Project); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *Project) GetByName(ctx context.Context, name string) (*domain.Project, error) {
	ret := _m.Called(ctx, name)

	var r0 *domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Project, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Project); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProjects provides a mock function with given fields: ctx, getProjectsRequest
func (_m *Project) GetProjects(ctx context.Context, getProjectsRequest *domain.GetProjectsRequest) ([]*domain.Project, error) {
	ret := _m.Called(ctx, getProjectsRequest)

	var r0 []*domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.GetProjectsRequest) ([]*domain.Project, error)); ok {
		return rf(ctx, getProjectsRequest)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.GetProjectsRequest) []*domain.Project); ok {
		r0 = rf(ctx, getProjectsRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.GetProjectsRequest) error); ok {
		r1 = rf(ctx, getProjectsRequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProject creates a new instance of Project. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProject(t interface {
	mock.TestingT
	Cleanup(func())
}) *Project {
	mock := &Project{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
