// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	domain "github.com/inquiryproj/inquiry/internal/notifiers/domain"
)

// Notifier is an autogenerated mock type for the Notifier type
type Notifier struct {
	mock.Mock
}

// SendCompletion provides a mock function with given fields: ctx, projectRun
func (_m *Notifier) SendCompletion(ctx context.Context, projectRun *domain.ProjectRun) error {
	ret := _m.Called(ctx, projectRun)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ProjectRun) error); ok {
		r0 = rf(ctx, projectRun)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotifier creates a new instance of Notifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Notifier {
	mock := &Notifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
